name: ReservasNE
main: io.github.LucasMullerC.ReservasNE.ReservasNE
version: 0.3.5
author: LucasMullerC
commands:
  add:
      description: Adicionar Reserva.
      usage: /add
      permission: reservasbte.add
  exibir:
      description: Exibir Regiao.
      usage: /<command> [regiao|rank]
  claim:
      description: Reservar.
      usage: /claim
  finalizar:
      description: Finalizar reserva.
      usage: /finalizar
  finalizar analise:
      description: Analisar reserva.
      usage: /finalizar reserva
      permission: reservasbte.review
  cancelar:
      description: Cancelar reserva.
      usage: /cancelar
  player:
      description: Add builder existente.
      usage: /player
      permission: reservasbte.player
  area:
      description: Comandos gerais de reserva.
      usage: /<command> [add|remover|aceitar|recusar|tp|coordenadas|Nick_do_jogador|tier4] Codigo
  salvar:
      description: Salvar dados.
      usage: /salvar
      permission: reservasbte.salvar
  reloadne:
      description: Recarregar.
      usage: /reloadne
      permission: reservasbte.admin
  link:
      description: Linkar Discord.
      usage: /link Nome_no_Discord
      