name: ReservasNE
main: io.github.LucasMullerC.ReservasNE.ReservasNE
version: 0.2.0
author: LucasMullerC
commands:
  add:
      description: Adicionar Reserva.
      usage: /add
      permission: reservasbte.add
  exibir:
      description: Exibir Regiao.
      usage: /<command> [regiao|rank]
  claim:
      description: Reservar.
      usage: /claim
  finalizar:
      description: Finalizar reserva.
      usage: /finalizar
  finalizar analise:
      description: Analisar reserva.
      usage: /finalizar reserva
      permission: reservasbte.review
  cancelar:
      description: Cancelar reserva.
      usage: /cancelar
  reserva:
      description: Gerenciar Reserva.
      usage: /<command> [aceitar|recusar|Nick_Jogador|tp|coordenadas]
  player:
      description: Add builder existente.
      usage: /player
      permission: reservasbte.player
  area:
      description: add area PRO e remover qualquer area.
      usage: /<command> [add|remover|tier4]
  salvar:
      description: Salvar dados.
      usage: /salvar
      permission: reservasbte.salvar
      